/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>

//Register Address
//RCC
#define RCC_Base 		0x40021000
#define RCC_APB2ENR 	*(volatile uint32_t*) (RCC_Base + 0x18)

//GPIO
#define GPIOA_Base 		0x40010800
#define GPIOA_CRH 		*(volatile uint32_t*) (GPIOA_Base + 0x04)
#define GPIOA_CRL 		*(volatile uint32_t*) (GPIOA_Base + 0x00)
#define GPIOA_ODR	 	*(volatile uint32_t*) (GPIOA_Base + 0x0C)
#define GPIOA_IDR 		*(volatile uint32_t*) (GPIOA_Base + 0x08)


#define GPIOB_Base 		0x40010C00
#define GPIOB_CRH 		*(volatile uint32_t*) (GPIOB_Base + 0x04)
#define GPIOB_CRL 		*(volatile uint32_t*) (GPIOB_Base + 0x00)
#define GPIOB_ODR	 	*(volatile uint32_t*) (GPIOB_Base + 0x0C)
#define GPIOB_IDR 		*(volatile uint32_t*) (GPIOB_Base + 0x08)

void clock_init()
{
	//Bit 2 IOPAEN: I/O port A clock enable
		RCC_APB2ENR |=(1<<2) ;
	//Bit 3 IOPBEN: I/O port B clock enable
		RCC_APB2ENR |=(1<<3);
}

void GPIO_init()
{
	GPIOA_CRL = 0x0;
	GPIOA_CRH = 0x0;
	GPIOB_CRL = 0x0;
	GPIOB_CRH = 0x0;

	//PA1 IN HighZ
	GPIOA_CRL |= (1<<6) ;
	//PB1 output push/pull mode
	GPIOB_CRL &= ~(0b11<<6); //CNF1 00: General purpose output push-pull
	GPIOB_CRL |= (0b01<<4) ; //01: Output mode, max speed 10 MHz.

	//PA13 IN HighZ
	GPIOA_CRH &= ~(0b11<<20);
	GPIOA_CRH |= (0b01<<22) ;
	//PB13 output push/pull mode
	GPIOB_CRH &= ~(0b11<<22); //CNF13-00: General purpose output push-pull
	GPIOB_CRH |= (0b01<<20) ; //MODE13-01: Output mode, max speed 10 MHz.
}

void wait(int x)
{
	unsigned int i ,j;
	for(i=0;i<x;i++)
		for(j=0;j<255;j++);
}
int main(void)
{
	clock_init();
	GPIO_init();

	while(1)
	{
		//PA1 >>>Connected external  PUR (default 1)
		if(((GPIOA_IDR & (1<<1)) >> 1) == 0) //Press
		{
			GPIOB_ODR ^= 1<<1;
			while(((GPIOA_IDR & (1<<1)) >> 1) == 0); //Single Press
		}

		//PA13 >>>Connected external  PDR (default 1)
		if(((GPIOA_IDR & (1<<13)) >> 13) == 1) //Multi Press
		{
			GPIOB_ODR ^= 1<<13;
		}
		wait(4);
	}
}
