/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>

//Register Address
//RCC
#define RCC_Base 		0x40021000
#define RCC_APB2ENR 	*(volatile uint32_t*) (RCC_Base + 0x18)
#define RCC_IOPAEN 		(1<<2)

//GPIO
#define GPIOA_Base 		0x40010800
#define GPIOA_CRH 		*(volatile uint32_t*) (GPIOA_Base + 0x04)
#define GPIOA_CRL 		*(volatile uint32_t*) (GPIOA_Base + 0x00)
#define GPIOA_ODR	 	*(volatile uint32_t*) (GPIOA_Base + 0x0C)

//EXTI
#define EXTI_Base 		0x40010400
#define EXTI_IMR		*(volatile uint32_t*) (EXTI_Base + 0x00)
#define EXTI_RTSR		*(volatile uint32_t*) (EXTI_Base + 0x08)
#define EXTI_PR			*(volatile uint32_t*) (EXTI_Base + 0x14)

//AFIO
#define AFIO_Base 		0x40010000
#define AFIO_EXTICR1	*(volatile uint32_t*) (AFIO_Base + 0x08)

//NVIC
#define NVIC_EXTIE0 	*(volatile uint32_t*) (0xE000E100)

void clock_init()
{
	//Enable clock GPIOA
	RCC_APB2ENR |=RCC_IOPAEN ;
	//Enable AFIOEN: Alternate function I/O clock enable
	RCC_APB2ENR |= (1<<0) ;
}

void GPIO_init()
{
	//PIN 13 PORT A output
	GPIOA_CRH &= 0xff0fffff;
	GPIOA_CRH |= 0x00200000;

	// pin A0  Floating input (reset state)
	GPIOA_CRL |= (1<<2);
}
int main(void)
{
	clock_init();
	GPIO_init();
	//EXTI x configuration (x= 0) to PORTA0
	AFIO_EXTICR1 =0;
	//Enable EXTI line 0 (Mask 1)
	EXTI_IMR |= (1>>0);

	//Enable Rising Trigger
	EXTI_RTSR |= (1>>0);

	//Enable NVIC IRQ6  <<>> EXTI0
	NVIC_EXTIE0 |= (1<<6);

	while(1);
}

void EXTI0_IRQHandler(void)
{
	//IQR Interrupt is happened EXTI0 >>port A Pin 0 _|-rising edge
	//toggle led pin A 13
	GPIOA_ODR ^= (1<<13);

	//Clear pending request for line 0----if not cleared will go on infinite interrupt
	EXTI_PR |= (1<<0);
}
